---
ansible_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

ansible_architecture_mapped: "{{ ansible_architecture_map[ansible_architecture] }}"

docker_registry: "127.0.0.1:5000"

users:
  - name: igor
    uid: 1000
    groups:
      - sudo
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA18c+RB3kzMyyM7Bz9wMIKONOnWjTQNgyuz0SyOL7EVBKutnQfXZyXFSqK9TL1sx9oJCUkI808GbB8+UdUOZEBmP50PEcMoma7mSVJJjwNQJEhU7wXjtir7HSSEW5nJAIwUqPBm5100mSeFrPKYuRjUmifxfCc/Iahqn3S6QzFiRc1Wy+RSoxZ7k8nOYjt5oCrIMFjuo0N1/GsSfP3q3N52J9fSVK2vSkCwXINo7WQ9JzWguQO5bgUkHA9j+wH2piWoo6UKX2TRV43VDbwXrb+lGThSijY0ztshAMiMhqH1quQU7zQWGD33c6G/EZJGzCcdUBKlHx+YWTL+Lix9I/kw=="
    shell: /bin/zsh
    state: present
  - name: buddy
    uid: 1100
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgha4S7e3e0fqjV6bAQqZyDPXBIGBXGPOwS4vVem2r0E5byMw5Dl+oU8lqrPhf/SizS3RxovjC+8kXx+q7Ypuz24NEvxtl2ghlUlFqieEwlPDDlXDH2SbW7NqZDOqgO4cMPwZ+PvE1k8ojj5FpEkkYNSRuf8D/hEp4Sycy6fiWGTc3EnXf3K/HbPWhEH2SNJ0+7aC8tnJTLQ0xMLYSIGmABpoWQP2BAryLrBEi4SnWhZOmibwUOsU6JKx6vHSKockX6H0HUa4wvRc1CG77pmBklqMJFPKEVPjaMTHe0TLrFWLBRZ71wY8eT5ZCiarPKIslQvVHdjzfry93XPDdmjnN"
    state: present
