---
- name: tuning kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ '/etc/sysctl.d/' + item.file }}"
    sysctl_set: yes
  with_items:
    - { name: 'vm.overcommit_memory', value: '1', file: '91-overcommit.conf' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '512', file: '92-tcp_max_syn_backlog.conf' }
    - { name: 'net.core.somaxconn', value: '512', file: '93-somaxconn.conf' }

- name: start container
  docker_container:
    name: redis
    image: redis:alpine
    command: redis-server --appendonly yes
    restart_policy: unless-stopped
    ports:
      - "{{ wireguard.ip + ':6379:6379/tcp' }}"
    volumes:
      - "/srv/redis/data:/data"
