---
- name: clone
  git:
    repo: https://github.com/zynaps/nginx.git
    dest: "{{ ansible_env.HOME + '/' + 'nginx' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'nginx' }}"
      pull: no
    name: "{{ docker_registry + '/' + 'nginx' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: create complementary nginx directory
  file:
    path: "/srv/nginx/etc/conf.d"
    state: directory

- name: create sites directories
  file:
    path: "/srv/sites/{{ item.0.name }}/{{ item.1 }}"
    state: directory
  loop: "{{ sites | product(['etc', 'files']) | list }}"

- name: generate sites configs
  template:
    dest: "/srv/sites/{{ item.name }}/etc/nginx.conf"
    src: templates/{{ item.template }}.conf.j2
  loop: "{{ sites }}"
  notify: reload nginx

- name: include sites configs
  copy:
    dest: /srv/nginx/etc/conf.d/sites.conf
    content: "include /srv/sites/*/etc/nginx.conf;\n"
  notify: reload nginx

- name: start container
  docker_container:
    name: nginx
    image: "{{ docker_registry + '/' + 'nginx' }}"
    restart_policy: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "/srv/nginx/etc/conf.d:/etc/nginx/conf.d"
      - "/srv/sites:/srv/sites"

- meta: flush_handlers
