---
- name: clone
  git:
    repo: https://github.com/zynaps/nginx.git
    dest: "{{ ansible_env.HOME + '/' + 'nginx' }}"

- name: build and push container
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'nginx' }}"
      pull: no
    name: "{{ docker.local_registry + '/' + 'nginx' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: start container
  docker_container:
    name: nginx
    image: "{{ docker.local_registry + '/' + 'nginx' }}"
    restart_policy: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - "/srv/nginx/sites.d:/etc/nginx/sites.d"
