---
- name: clone
  git:
    repo: https://github.com/zynaps/nginx.git
    dest: "{{ ansible_env.HOME + '/' + 'nginx' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'nginx' }}"
      pull: no
    name: "{{ docker_registry + '/' + 'nginx' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: start container
  docker_container:
    name: nginx
    image: "{{ docker_registry + '/' + 'nginx' }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable=true
      traefik.http.routers.sites.rule=Host(`zynaps.ru`)
      traefik.http.routers.sites.tls=true
      traefik.http.routers.sites.tls.certresolver=letsencrypt
    volumes:
      - "/srv/sites:/sites"
