---
- name: clone
  git:
    repo: https://github.com/zynaps/nginx.git
    dest: "{{ ansible_env.HOME + '/' + 'nginx' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'nginx' }}"
      pull: no
    name: "{{ docker_registry + '/' + 'nginx' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: create sites data directories
  file:
    path: "{{ '/srv/sites/' + item.domain + '/data' }}"
    state: directory
  loop: "{{ sites }}"

- name: create sites config directory
  file:
    path: /srv/nginx/sites.d
    state: directory

- name: generate vhosts configs
  template:
    dest: "/srv/nginx/sites.d/{{ item.domain }}.conf"
    src: templates/vhost.conf.j2
  loop: "{{ sites }}"
  notify: reload nginx

- name: start container
  docker_container:
    name: nginx
    image: "{{ docker_registry + '/' + 'nginx' }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable=true
      traefik.http.routers.sites.rule=Host(`{{ sites | map(attribute='domain') | join('`,`') }}`)
      traefik.http.routers.sites.tls=true
      traefik.http.routers.sites.tls.certresolver=letsencrypt
    volumes:
      - "/srv/nginx/sites.d:/etc/nginx/sites.d"
      - "/srv/sites:/sites"

- meta: flush_handlers
