---
- name: install python addons
  apt:
    name: [
      'python-apt',
      'python-pip'
    ]

- name: install user packages
  apt:
    name: [
      'curl',
      'dnsutils',
      'git',
      'htop',
      'iperf3',
      'jq',
      'rsync',
      'socat',
      'tcpdump',
      'tmux',
      'vim',
      'whois',
      'zsh'
    ]
