---
- name: install
  apt:
    name:
      - curl
      - direnv
      - git
      - htop
      - iptables
      - jq
      - netcat-openbsd
      - nmap
      - python3-pip
      - rclone
      - restic
      - rsync
      - socat
      - sudo
      - tcpdump
      - tmux
      - vim
      - whois
      - zsh
