---
- name: install users packages
  apt:
    name:
      - curl
      - fping
      - fswatch
      - git
      - htop
      - iperf3
      - iptables
      - jq
      - ncat
      - nmap
      - python3-pip
      - rclone
      - restic
      - rsync
      - socat
      - sudo
      - tcpdump
      - tmux
      - tree
      - tshark
      - vim
      - whois
      - zsh
