---
- name: install users packages
  apt:
    name: [
      'curl',
      'dnsutils',
      'git',
      'htop',
      'iperf3',
      'jq',
      'man-db',
      'rsync',
      'socat',
      'sudo',
      'tcpdump',
      'tmux',
      'tree',
      'vim',
      'whois',
      'zsh'
    ]
