---
- name: install
  apt:
    name: vnstat

- name: configure
  lineinfile:
    dest: /etc/vnstat.conf
    regexp: "^#? *{{ item.key|regex_escape() }} "
    line: "{{ item.key }} {{ item.value }}"
  loop:
    - { key: 'MonthFormat', value: '"%b %Y"' }
    - { key: 'UnitMode', value: '1' }
    - { key: 'HourlyDecimals', value: '2' }
    - { key: 'MaxBandwidth', value: '0' }
  notify: restart vnstat

- meta: flush_handlers
