---
- name: install
  apt:
    name: vnstat

- name: configure
  lineinfile:
    dest: /etc/vnstat.conf
    regexp: "^#? *{{ item.key|regex_escape() }} "
    line: "{{ item.key }} {{ item.value }}"
  with_dict:
    'MonthFormat': '"%b %Y"'
    'UnitMode': 1
    'HourlyDecimals': 2
    'MaxBandwidth': 0
  notify: restart vnstat

- meta: flush_handlers
