---
- name: roles applicable on any host
  hosts: all
  become: yes

  roles:
    - apt_update
    - common_packages
    - vnstat
    - wireguard
    - docker
    - docker_registry
    - node_exporter
    - users
