---
- name: dotfiles for current user and zsh as shell
  hosts: all

  tasks:
    - name: checkout Oh My Zsh
      git:
        accept_hostkey: true
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ ansible_env.HOME + '/.oh-my-zsh' }}"

    - name: clone bare dotfiles repository
      git:
        accept_hostkey: true
        repo: https://github.com/zynaps/dotfiles.git
        dest: "{{ ansible_env.HOME + '/.dotfiles' }}"
        bare: yes
      register: update_dotfiles

    - name: hide untracked files
      git_config:
        repo: "{{ ansible_env.HOME + '/.dotfiles' }}"
        scope: local
        name: status.showUntrackedFiles
        value: 'no'

    - name: forced checkout base dotfiles
      shell: git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout --force
      when: update_dotfiles.changed

    - name: precreate sensetive files
      file:
        path: "{{ ansible_env.HOME + item }}"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve
      with_items:
        - "{{ '/.lesshst' }}"
        - "{{ '/.viminfo' }}"

    - name: set zsh as shell
      become: yes
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
