---
- name: manage dotfiles
  hosts: all

  tasks:
    - name: get starship current version info
      command: starship --version
      register: starship_current_info
      changed_when: no
      failed_when: no

    - name: starship is not installed
      set_fact:
        starship_current: '0.0'
      when: starship_current_info.rc == 2

    - name: extract starship current version
      set_fact:
        starship_current: "{{ starship_current_info.stdout|regex_search('starship ([\\d\\.]+)', '\\1')|first }}"
      when: starship_current_info.rc == 0

    - name: get starship latest version info
      uri:
        url: https://api.github.com/repos/starship/starship/releases/latest
      register: starship_latest_info
      changed_when: no
      failed_when: no

    - name: extract starship latest version
      set_fact:
        starship_latest: "{{ starship_latest_info.json.tag_name|regex_search('^v([\\d\\.]+)$', '\\1')|first }}"

    - name: install starship
      become: yes
      unarchive:
        dest: /usr/bin
        src: "https://github.com/starship/starship/releases/download/v{{ starship_latest }}/starship-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        remote_src: yes
      when: starship_latest is version(starship_current, 'gt')

    - name: get chezmoi current version info
      command: chezmoi --version
      register: chezmoi_current_info
      changed_when: no
      failed_when: no

    - name: chezmoi is not installed
      set_fact:
        chezmoi_current: '0.0'
      when: chezmoi_current_info.rc == 2

    - name: extract chezmoi current version
      set_fact:
        chezmoi_current: "{{ chezmoi_current_info.stdout|regex_search('version v([\\d\\.]+),', '\\1')|first }}"
      when: chezmoi_current_info.rc == 0

    - name: get chezmoi latest version info
      uri:
        url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
      register: chezmoi_latest_info
      changed_when: no
      failed_when: no

    - name: extract chezmoi latest version
      set_fact:
        chezmoi_latest: "{{ chezmoi_latest_info.json.tag_name|regex_search('^v([\\d\\.]+)$', '\\1')|first }}"

    - name: install chezmoi
      become: yes
      apt:
        deb: "https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_latest }}/chezmoi_{{ chezmoi_latest }}_linux_{{ ansible_architecture_mapped }}.deb"
      when: chezmoi_latest is version(chezmoi_current, 'gt')

    - name: check for chezmoi config
      stat:
        path: "{{ ansible_env.HOME + '/.local/share/chezmoi/.git/index' }}"
      register: chezmoi_git_index

    - name: add dotfiles to chezmoi
      command: chezmoi init --no-tty --force --apply zynaps
      when: not chezmoi_git_index.stat.exists

    - name: update dotfiles and externals
      command: chezmoi update --no-tty --force --refresh-externals
      when: chezmoi_git_index.stat.exists
