---
- name: dotfiles for regular user
  hosts: all

  tasks:
    - name: checkout helper modules
      git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_env.HOME + '/' + item.dest }}"
      with_items:
        - { repo: 'https://github.com/robbyrussell/oh-my-zsh', dest: '.oh-my-zsh' }
        - { repo: 'https://github.com/tpope/vim-pathogen', dest: '.vim/bundle/vim-pathogen' }
        - { repo: 'https://github.com/chriskempson/base16-vim', dest: '.vim/bundle/base16-vim' }
        - { repo: 'https://github.com/tpope/vim-repeat', dest: '.vim/bundle/vim-repeat' }
        - { repo: 'https://github.com/tpope/vim-commentary', dest: '.vim/bundle/vim-commentary' }
        - { repo: 'https://github.com/ntpeters/vim-better-whitespace', dest: '.vim/bundle/vim-better-whitespace' }
        - { repo: 'https://github.com/now/vim-restore-position', dest: '.vim/bundle/vim-restore-position' }

    - name: clone bare dotfiles repository
      git:
        repo: https://github.com/zynaps/dotfiles.git
        dest: "{{ ansible_env.HOME + '/' + '.dotfiles' }}"
        bare: yes

    - name: hide untracked files
      git_config:
        repo: "{{ ansible_env.HOME + '/' + '.dotfiles' }}"
        scope: local
        name: status.showUntrackedFiles
        value: 'no'

    - name: checkout base dotfiles
      shell: |
        git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout

    - name: pre create sensetive files
      file:
        path: "{{ item }}"
        mode: 0600
        state: touch
      with_items:
        - "{{ '.lesshst' }}"
        - "{{ '.viminfo' }}"
