---
- name: manage dotfiles
  hosts: all

  roles:
    - starship
    - chezmoi

  tasks:
    - name: preserve sensitive files
      file:
        path: "{{ item }}"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve
      loop:
        - .lesshst
        - .viminfo
        - .z

    - name: check for chezmoi config
      stat:
        path: "{{ ansible_env.HOME + '/.local/share/chezmoi/.git/index' }}"
      register: chezmoi_git_index

    - name: add dotfiles and externals
      command: chezmoi init --no-tty --force --apply zynaps
      when: not chezmoi_git_index.stat.exists

    - name: update dotfiles and externals
      command: chezmoi update --no-tty --force --refresh-externals
      when: chezmoi_git_index.stat.exists
