---
- name: dotfiles for regular user
  hosts: all

  tasks:
    - name: checkout Oh My Zsh
      git:
        accept_hostkey: true
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ ansible_env.HOME + '/.oh-my-zsh' }}"

    - name: clone bare dotfiles repository
      git:
        accept_hostkey: true
        repo: https://github.com/zynaps/dotfiles.git
        dest: "{{ ansible_env.HOME + '/.dotfiles' }}"
        bare: yes

    - name: hide untracked files
      git_config:
        repo: "{{ ansible_env.HOME + '/.dotfiles' }}"
        scope: local
        name: status.showUntrackedFiles
        value: 'no'

    - name: forced checkout base dotfiles
      shell: |
        git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout --force

    - name: pre create sensetive files
      file:
        path: "{{ item }}"
        mode: 0600
        state: touch
      with_items:
        - "{{ '.lesshst' }}"
        - "{{ '.viminfo' }}"
