---
- import_playbook: common_roles.yml

- name: escape setup
  hosts: escape.zynaps.ru
  become: yes

  roles:
    - router
    - docker_registry
    - postfix
    - redis
    - rutor_watch
    - nginx
    - feeder
