---
- import_playbook: bootstrap.yml

- name: escape setup
  hosts: escape
  become: yes

  roles:
    - alertmanager
    - prometheus
    - grafana
    - redis
    - rutor_watch
    - feeder
    - traefik
