---
- name: escape setup
  hosts: escape
  become: yes

  roles:
    - common_packages
    - wireguard
    - docker
    - registry
    - postfix
    - redis
    - rutor_watch
    - feeder
    - nginx
    - mtg
