---
- name: escape setup
  hosts: escape
  become: yes

  roles:
    - apt_update
    - docker
    - docker_registry
    - node_exporter
    - alertmanager
    - prometheus
    - grafana
    - redis
    - rutor_watch
    - feeder
    - traefik
    - nginx
