---
- name: escape setup
  hosts: escape
  become: yes

  roles:
    - qemu_guest_agent
    - router
    - common_packages
    - vnstat
    - wireguard
    - docker
    - node_exporter
    - docker_registry
    - postfix
    - redis
    - rutor_watch
    - nginx
    - feeder
