---
- name: escape setup
  hosts: escape
  become: yes

  roles:
    - router
    - common_packages
    - vnstat
    - wireguard
    - docker
    - registry
    - postfix
    - redis
    - rutor_watch
    - nginx
    - feeder
    - plex
    - transmission
