version: '3'

vars:
  DOMAIN: zynaps.ru

tasks:
  host:add:
    desc: add host common playbook and wireguard variables
    cmds:
      - bin/host_add.sh {{.CLI_ARGS}}

  host:bootstrap:
    desc: install python with necessary libs, full upgrade host, add users
    cmds:
      - ansible-playbook bootstrap.yml --limit {{.CLI_ARGS}}.{{.DOMAIN}}

  host:setup:
    desc: setup usual roles and declarated roles in host playbook
    cmds:
      - ansible-playbook usual_roles.yml {{.CLI_ARGS}}.{{.DOMAIN}}.yml --limit {{.CLI_ARGS}}.{{.DOMAIN}}

  dotfiles:add:
    desc: install dotfiles on a empty home
    cmds:
      - ssh {{.CLI_ARGS}}.{{.DOMAIN}} chezmoi init --apply zynaps

  dotfiles:changes:
    desc: see changes without actually applying them
    cmds:
      - ssh {{.CLI_ARGS}}.{{.DOMAIN}} chezmoi git pull -- --rebase
      - ssh {{.CLI_ARGS}}.{{.DOMAIN}} chezmoi diff

  dotfiles:update:
    desc: updating dotfiles and externals
    cmds:
      - ssh {{.CLI_ARGS}}.{{.DOMAIN}} chezmoi update --refresh-externals
