version: '3'

tasks:
  host:add:
    desc: add host common playbook and wireguard variables
    cmds:
      - bin/host_add.sh {{.CLI_ARGS}}

  host:setup:
    desc: setup common roles and declarated roles in host playbook
    cmds:
      - ansible-playbook {{.CLI_ARGS}}.yml --limit {{.CLI_ARGS}}

  user:dotfiles:
    desc: add dotfiles and chezmoi to manage them
    cmds:
      - ansible-playbook dotfiles.yml --limit {{.CLI_ARGS}}
