version: '3'

tasks:
  host:add:
    desc: add host common playbook and wireguard variables
    cmds:
      - bin/host_add.sh {{.CLI_ARGS}}

  host:bootstrap:
    desc: install python with necessary libs, full upgrade host, add users
    cmds:
      - ansible-playbook bootstrap.yml --limit {{.CLI_ARGS}}

  host:setup:
    desc: setup common roles and declarated roles in host playbook
    cmds:
      - ansible-playbook {{.CLI_ARGS}}.yml --limit {{.CLI_ARGS}}

  dotfiles:add:
    desc: install dotfiles on a empty home
    cmds:
      - ssh {{.CLI_ARGS}} chezmoi init --apply zynaps

  dotfiles:changes:
    desc: see changes without actually applying them
    cmds:
      - ssh {{.CLI_ARGS}} chezmoi git pull -- --rebase
      - ssh {{.CLI_ARGS}} chezmoi diff

  dotfiles:update:
    desc: updating dotfiles and externals
    cmds:
      - ssh {{.CLI_ARGS}} chezmoi update --refresh-externals
