---
- name: clone
  git:
    repo: https://github.com/zynaps/rutor_watch.git
    dest: "{{ ansible_env.HOME + '/' + 'rutor_watch' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'rutor_watch' }}"
      pull: no
    name: "{{ docker.registry + '/' + 'rutor_watch' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: start container
  docker_container:
    name: rutor_watch
    image: "{{ docker.registry + '/' + 'rutor_watch' }}"
    restart_policy: unless-stopped
    env:
      REDIS_URL: "redis://redis:6379"
