---
- name: clone
  git:
    repo: https://github.com/zynaps/postfix.git
    dest: "{{ ansible_env.HOME + '/' + 'postfix' }}"

- name: build and push container
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'postfix' }}"
      pull: no
    name: "{{ docker.local_registry + '/' + 'postfix' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: create directories
  file:
    path: "{{ '/srv/postfix/' + item }}"
    state: directory
  with_items:
    - config
    - spool

- name: add config
  template:
    src: templates/configure.sh.j2
    dest: /srv/postfix/config/configure.sh
    mode: 0600
  notify: reload postfix

- name: start container
  docker_container:
    name: postfix
    image: "{{ docker.local_registry + '/' + 'postfix' }}"
    pull: yes
    restart_policy: unless-stopped
    ports:
      - "95.179.193.231:25:25/tcp"
    volumes:
      - "/srv/postfix/config/configure.sh:/configure.sh"
      - "/srv/postfix/spool:/var/spool/postfix"

- meta: flush_handlers
