---
- name: clone postfix
  git:
    repo: https://github.com/zynaps/postfix.git
    dest: "{{ ansible_env.HOME + '/' + 'postfix' }}"

- name: build and push postfix container
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'postfix' }}"
      pull: no
    name: "{{ docker.local_registry + '/' + 'postfix' }}"
    push: yes
    state: present
    force_source: yes
    source: build

- name: copy postfix configuration script
  copy:
    src: files/update_config.sh
    dest: /srv/postfix/update_config.sh
    mode: 0700
  register: update_config

- name: start postfix container
  docker_container:
    name: postfix
    image: "{{ docker.local_registry + '/' + 'postfix' }}"
    pull: yes
    restart_policy: unless-stopped
    ports:
      - "95.179.193.231:25:25/tcp"
    volumes:
      - "/srv/postfix/update_config.sh:/etc/postfix/update_config.sh"
      - "/srv/postfix/spool:/var/spool/postfix"

- name: update postfix config
  shell: docker exec postfix /etc/postfix/update_config.sh

- name: postfix reload
  shell: docker exec postfix postfix reload
  when: update_config.changed
