apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.wg0.zynaps.ru:9090
    isDefault: true
    version: 1
    editable: false
    uid: prometheus_uid
