---
- name: clone
  git:
    repo: https://github.com/zynaps/feeder.git
    dest: "{{ ansible_env.HOME + '/' + 'feeder' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'feeder' }}"
      pull: no
    name: "{{ docker.registry + '/' + 'feeder' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: start container
  docker_container:
    name: feeder
    image: "{{ docker.registry + '/' + 'feeder' }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable=true
      traefik.http.routers.feeder.rule=Host(`feeder.zynaps.ru`)
      traefik.http.routers.feeder.tls=true
      traefik.http.routers.feeder.tls.certresolver=letsencrypt
    env:
      REDIS_URL: "redis://redis.wg0.zynaps.ru:6379"
