---
- name: clone
  git:
    repo: https://github.com/zynaps/feeder.git
    dest: "{{ ansible_env.HOME + '/' + 'feeder' }}"

- name: build and push container
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'feeder' }}"
      pull: no
    name: "{{ docker.local_registry + '/' + 'feeder' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: start container
  docker_container:
    name: feeder
    image: "{{ docker.local_registry + '/' + 'feeder' }}"
    restart_policy: unless-stopped
    ports:
      - "{{ wireguard.ip + ':4567:4567/tcp' }}"
    env:
      REDIS_URL: "{{ 'redis://' + hostvars['escape'].wireguard.ip + ':6379' }}"

- name: add nginx config
  template:
    dest: /srv/nginx/sites.d/feeder.conf
    src: templates/nginx.conf.j2
  notify: reload nginx

- meta: flush_handlers
