---
- name: clone
  git:
    repo: https://github.com/zynaps/transmission.git
    dest: "{{ ansible_env.HOME + '/' + 'transmission' }}"

- name: build and push image
  docker_image:
    build:
      path: "{{ ansible_env.HOME + '/' + 'transmission' }}"
      pull: no
    name: "{{ docker_registry + '/' + 'transmission' }}"
    push: yes
    source: build
    force_source: yes
    state: present

- name: create directories
  file:
    path: "{{ '/srv/transmission/' + item }}"
    state: directory
  loop:
    - watch
    - incomplete
    - complete

- name: change permissions for watch directory
  file:
    path: /srv/transmission/watch
    mode: 0777

- name: tuning kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ '/etc/sysctl.d/90-' + item.name|split('.')|last + '.conf' }}"
    sysctl_set: yes
  loop:
    - { name: 'net.core.rmem_max', value: '4194304' }
    - { name: 'net.core.wmem_max', value: '1048576' }

- name: start container
  docker_container:
    name: transmission
    image: "{{ docker_registry + '/' + 'transmission' }}"
    restart_policy: unless-stopped
    ports:
      - "{{ wireguard_ip + ':9091:9091/tcp' }}"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    volumes:
      - "/srv/transmission/watch:/watch"
      - "/srv/transmission/incomplete:/incomplete"
      - "/srv/transmission/complete:/complete"
      - "/srv/plex/media/movies:/movies"
