---
- name: create node_exporter user
  user:
    name: node_exporter
    comment: node_exporter daemon
    create_home: no
    system: yes
    shell: /usr/sbin/nologin
    state: present

- name: download and extract
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
    dest: /tmp
    mode: 0755
    remote_src: true

- name: install binary
  copy:
    src: /tmp/node_exporter-1.2.2.linux-amd64/node_exporter
    dest: /usr/bin
    mode: 0755
    remote_src: true
  notify: restart node_exporter

- name: systemd unit file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify: restart node_exporter

- name: enable and start service
  service:
    name: node_exporter
    state: started
    enabled: yes

- meta: flush_handlers
