---
- name: passwordless sudo for sudo group
  copy:
    dest: /etc/sudoers.d/99-sudo-nopasswd
    content: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL\n"
    mode: 0440

- name: add or delete
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups | default('') }}"
    shell: "{{ item.shell | default('/bin/sh') }}"
    state: "{{ item.state }}"
    remove: yes
  loop: "{{ users }}"

- name: add authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
    state: present
  when: item.state == 'present' and item.authorized_key is defined
  loop: "{{ users }}"
