---
- name: start mtg proxy
  docker_container:
    name: mtg
    image: nineseconds/mtg:stable
    command: run "{{ mtg_secret }}"
    restart_policy: unless-stopped
    ports:
      - "3128:3128/tcp"
