---
- name: create directories
  file:
    path: "{{ '/srv/prometheus/' + item }}"
    state: directory
  loop:
    - etc
    - data

- name: add recording and alerting rules
  copy:
    dest: /srv/prometheus/etc
    src: files/rules.d
  notify: restart prometheus

- name: add config
  template:
    src: templates/prometheus.yml.j2
    dest: /srv/prometheus/etc/prometheus.yml
  notify: restart prometheus

- name: start container
  docker_container:
    name: prometheus
    image: prom/prometheus
    restart_policy: unless-stopped
    hostname: prometheus
    user: root
    ports:
      - "{{ wireguard.ip + ':9090:9090/tcp' }}"
    volumes:
      - "/srv/prometheus/etc/rules.d:/etc/prometheus/rules.d"
      - "/srv/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/srv/prometheus/data:/prometheus"

- meta: flush_handlers
