---
- name: add install prerequisites
  apt:
    name: [
      'apt-transport-https',
      'software-properties-common',
    ]

- name: add GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/debian/gpg"

- name: add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: install docker-ce
  apt:
    name: docker-ce

- name: add runtime prerequisites
  pip:
    name:
      'docker'

- name: add base config
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-file": "3",
          "max-size": "32m"
        }
      }
    dest: /etc/docker/daemon.json
    mode: 0600
  notify: restart docker

- name: enable and start service
  systemd:
    name: docker
    state: started
    enabled: yes

- meta: flush_handlers
