---
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - software-properties-common

- name: add GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: add repository
  apt_repository:
    repo: deb [arch={{ ansible_architecture_mapped }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: install
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - python3-docker

- name: add config
  template:
    dest: /etc/docker/daemon.json
    src: templates/daemon.json.j2
    mode: 0600
  notify: restart docker

- name: enable and start service
  systemd:
    name: docker
    state: started
    enabled: yes

- meta: flush_handlers
