---
- name: create user
  user:
    name: plex
    comment: plex media server
    create_home: no
    system: yes
    home: /srv/plex
    shell: /usr/sbin/nologin
    state: present
  register: plex_user

- name: create directories
  file:
    path: "{{ '/srv/plex/' + item }}"
    owner: plex
    group: plex
    mode: 0775
    state: directory
  loop:
    - etc
    - data/movies
    - data/music
    - data/photos
    - data/shows

- name: start container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    restart_policy: unless-stopped
    env:
      PLEX_UID: "{{ plex_user.uid }}"
      PLEX_GID: "{{ plex_user.group }}"
    ports:
      - "32400:32400/tcp"
    volumes:
      - "/srv/plex/etc:/config"
      - "/srv/plex/data:/data"
