---
- name: create directories
  file:
    path: "{{ '/srv/plex/' + item }}"
    state: directory
  with_items:
    - config
    - media/movies
    - media/music
    - media/photos
    - media/shows

- name: start container
  docker_container:
    name: plex
    image: wernight/plex-media-server
    restart_policy: unless-stopped
    user: root
    ports:
      - "32400:32400/tcp"
    volumes:
      - "/srv/plex/config:/config"
      - "/srv/plex/media:/media"
