---
- name: install kernel modules
  apt:
    name: wireguard
  when: ansible_kernel is version('5.6', '<')

- name: install tools
  apt:
    name: wireguard-tools

- name: create config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: add config
  template:
    dest: /etc/wireguard/wg0.conf
    src: templates/wg0.conf.j2
    mode: 0600
  notify: restart wireguard

- name: enable and start service
  systemd:
    service: wg-quick@wg0
    enabled: yes
    state: started
    daemon_reload: yes

- meta: flush_handlers
