---
- name: set limit for unstable packages
  copy:
    dest: /etc/apt/preferences.d/limit-unstable
    content: "Package: *\nPin: release a=unstable\nPin-Priority: 90\n"

- name: add wireguard repository
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    filename: unstable-wireguard

- name: install wireguard toolkit
  apt:
    name: wireguard

- name: add wireguard interface config
  template:
    dest: /etc/network/interfaces.d/wg0.conf
    src: templates/wg0_interface.j2

- name: make wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: add wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: templates/wg0_config.j2
    mode: 0600

- name: add boot-time iptables rules loader
  apt:
    name: [
      'iptables-persistent'
    ]
  when: wireguard.exit_node is defined and wireguard.exit_node

- name: add masquerade at exit node
  iptables_raw:
    name: masquerade for wireguard peers
    table: nat
    rules: |
      -A POSTROUTING -s 10.7.0.0/24 -o en+ -j MASQUERADE
  when: wireguard.exit_node is defined and wireguard.exit_node

- name: add forwarding for wireguard peers
  iptables_raw:
    name: forwarding for wireguard peers
    rules: |
      -A INPUT -i wg0 -j ACCEPT
      -A FORWARD -i wg0 -j ACCEPT
  when: wireguard.exit_node is defined and wireguard.exit_node

- name: enable routing at exit node
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/90-ip_forward.conf
    sysctl_set: yes
  when: wireguard.exit_node is defined and wireguard.exit_node

- name: restart wireguard interface
  shell: |
    ifquery wg0 && ifdown --force --ignore-errors wg0 && sleep 1
    ifup --force --ignore-errors wg0
