---
- name: install wireguard toolkit
  apt:
    name: wireguard

- name: add wireguard interface config
  template:
    dest: /etc/network/interfaces.d/wg0.conf
    src: templates/wg0_interface.j2
  register: update_wireguard_config

- name: make wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700
  register: update_wireguard_config

- name: add wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: templates/wg0_config.j2
    mode: 0600
  register: update_wireguard_config
  no_log: true

- name: restart wireguard interface
  shell: |
    ifquery wg0 && ifdown --force --ignore-errors wg0 && sleep 1
    ifup --force --ignore-errors wg0
  when: update_wireguard_config
