---
- name: set limit for unstable packages
  copy:
    dest: /etc/apt/preferences.d/limit-unstable
    content: "Package: *\nPin: release a=unstable\nPin-Priority: 90\n"

- name: add wireguard repository
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    filename: unstable-wireguard

- name: install wireguard toolkit
  apt:
    name: wireguard

- name: add wireguard interface config
  template:
    dest: /etc/network/interfaces.d/wg0.conf
    src: templates/wg0_interface.j2

- name: make wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: add wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: templates/wg0_config.j2
    mode: 0600

- name: restart wireguard interface
  shell: |
    ifquery wg0 && ifdown --force --ignore-errors wg0 && sleep 1
    ifup --force --ignore-errors wg0
