---
- name: install wireguard kernel modules
  apt:
    name: wireguard
  when: ansible_kernel is version('5.6', '<')

- name: install wireguard tools
  apt:
    name: wireguard-tools

- name: make wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: add wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: templates/wg0.conf.j2
    mode: 0600
  notify: restart wireguard
  no_log: true

- name: enable and start wireguard
  systemd:
    service: wg-quick@wg0
    enabled: yes
    daemon_reload: yes
    state: started

- meta: flush_handlers
