---
- block:
  - block:
    - name: install QEMU guest agent
      apt:
        name: 'qemu-guest-agent'

    - name: enable and start agent
      systemd:
        name: 'qemu-guest-agent'
        state: started
        enabled: yes
    when: ansible_virtualization_type == 'kvm'

  - block:
    - name: install VMware guest agent
      apt:
        name: open-vm-tools
    when: ansible_virtualization_type | lower == 'vmware'
  when: ansible_virtualization_role == 'guest'
